### ISSUE TITLE
Complete The Read Me file 

### ISSUE THREAD

**Issue by sacrilegioushero220** [sacrilegioushero220/IEEE-MBCCET-SB-WEBSITE#1]
The Template of the Read Me file is in the main repo. By making the changes we need to add information about our project in the Read Me file using that Template

**Comment by ghubrakesh** [comment]
Hello @sacrilegioushero220, I would like to contribute to your project. Please assign me the same.

**Comment by abhi87374** [comment]
can you assign this task to me and explain a bit about what info to add

**Comment by sacrilegioushero220** [comment]
This is about creating a website for our IEEE Student Branch of Mar Baselios Christian College of engineering and technology.
This website contains all the information regarding our student branch
